import Head from 'next/head';
import Footer from '@/components/footer';
import { Button, Heading } from '@chakra-ui/react';

import styles from '@/styles/Home.module.css';

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Heading as="h3" size="lg">
          In ❤️ with React & Next with Chakra UI
        </Heading>
        <br />
        <Button size="lg" colorScheme="green" mt="24px">
          Let's get started
        </Button>
      </main>
      <Footer />
    </div>
  );
};

export default Home;
